# Generated by Django 2.2 on 2020-03-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_antiga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='titulo',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
