# Generated by Django 2.2 on 2020-04-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_funcionario_de_ferias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='user',
            field=models.IntegerField(verbose_name='Código do Usuário'),
        ),
    ]
