# Generated by Django 2.2 on 2020-02-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0003_registro_hora_extra_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_hora_extra',
            name='utilizada',
            field=models.BooleanField(default=False),
        ),
    ]
